[package]
name = "data-gator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = {version="1.0", features = ["derive"]}
colored = "2.1.0"
tokio = {version="1.38", features = ["full"]}